import type { Note } from '../types/note'
const DATABASE_NAME='key3in-offline',DATABASE_VERSION=2,NOTES_STORE='notes',QUEUE_STORE='syncQueue'
export interface PendingChange{key:string;userId:number;date:string;text:string|null;queuedAt:string}
const keyOf=(userId:number,date:string)=>`${userId}:${date}`
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE_NAME,DATABASE_VERSION);request.onupgradeneeded=()=>{const db=request.result;for(const name of [NOTES_STORE,QUEUE_STORE])if(db.objectStoreNames.contains(name))db.deleteObjectStore(name);db.createObjectStore(NOTES_STORE,{keyPath:'cache_key'});db.createObjectStore(QUEUE_STORE,{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function all<T>(storeName:string):Promise<T[]>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readonly'),request=tx.objectStore(storeName).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
export async function getCachedMonth(userId:number,month:string){return (await all<Note>(NOTES_STORE)).filter(n=>n.cache_key?.startsWith(`${userId}:`)&&n.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date))}
export async function getPendingChanges(userId:number){return (await all<PendingChange>(QUEUE_STORE)).filter(c=>c.userId===userId).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))}
export async function replaceCachedMonth(userId:number,month:string,notes:Note[]){const existing=await getCachedMonth(userId,month),pending=await getPendingChanges(userId),pendingDates=new Set(pending.map(c=>c.date)),db=await openDatabase();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(NOTES_STORE,'readwrite'),store=tx.objectStore(NOTES_STORE);existing.filter(n=>!pendingDates.has(n.date)||n.user_id!==userId).forEach(n=>store.delete(n.cache_key!));notes.forEach(n=>{if(n.user_id!==userId||!pendingDates.has(n.date))store.put({...n,cache_key:keyOf(userId,`${n.date}:${n.user_id}`)})});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)})}
export async function saveOfflineNote(userId:number,userName:string,userColor:string,date:string,text:string){const normalized=text.trim(),now=new Date().toISOString(),key=keyOf(userId,date),db=await openDatabase();return new Promise<Note|undefined>((resolve,reject)=>{const tx=db.transaction([NOTES_STORE,QUEUE_STORE],'readwrite'),notes=tx.objectStore(NOTES_STORE),queue=tx.objectStore(QUEUE_STORE);let saved:Note|undefined;const request=notes.get(keyOf(userId,`${date}:${userId}`));request.onsuccess=()=>{const previous=request.result as Note|undefined;if(normalized){saved={id:previous?.id??-Date.now(),date,user_id:userId,user_name:userName,user_color:userColor,text:normalized,created_at:previous?.created_at??now,updated_at:now,cache_key:keyOf(userId,`${date}:${userId}`)};notes.put(saved)}else notes.delete(keyOf(userId,`${date}:${userId}`));queue.put({key,userId,date,text:normalized||null,queuedAt:now} satisfies PendingChange)};tx.oncomplete=()=>{db.close();resolve(saved)};tx.onerror=()=>reject(tx.error)})}
export async function completeChange(change:PendingChange,serverNote?:Note){const db=await openDatabase();return new Promise<boolean>((resolve,reject)=>{const tx=db.transaction([NOTES_STORE,QUEUE_STORE],'readwrite'),notes=tx.objectStore(NOTES_STORE),queue=tx.objectStore(QUEUE_STORE);let done=false,request=queue.get(change.key);request.onsuccess=()=>{const current=request.result as PendingChange|undefined;if(current?.queuedAt!==change.queuedAt)return;const noteKey=keyOf(change.userId,`${change.date}:${change.userId}`);if(serverNote)notes.put({...serverNote,cache_key:noteKey});else notes.delete(noteKey);queue.delete(change.key);done=true};tx.oncomplete=()=>{db.close();resolve(done)};tx.onerror=()=>reject(tx.error)})}
export async function searchCachedNotes(userId:number,query:string){const normalized=query.toLocaleLowerCase('ru-RU');return (await all<Note>(NOTES_STORE)).filter(n=>n.cache_key?.startsWith(`${userId}:`)&&n.text.toLocaleLowerCase('ru-RU').includes(normalized)).sort((a,b)=>a.date.localeCompare(b.date))}
export async function getCachedDate(userId:number,date:string){return (await all<Note>(NOTES_STORE)).filter(n=>n.cache_key?.startsWith(`${userId}:`)&&n.date===date)}
