import {useCallback,useEffect,useMemo,useRef,useState} from 'react';import {Alert,Box,CircularProgress,Snackbar} from '@mui/material';import {AuthScreen} from './components/AuthScreen';import {CalendarHeader} from './components/CalendarHeader';import {CalendarGrid} from './components/CalendarGrid';import {NoteEditor} from './components/NoteEditor';import {NotificationsView} from './components/NotificationsView';import {SearchView} from './components/SearchView';import {SettingsView} from './components/SettingsView';import {RecurringEventsView} from './components/RecurringEventsView';import {useOnlineStatus} from './hooks/useOnlineStatus';import {useSwipe} from './hooks/useSwipe';import {api,ApiError,getToken,setToken} from './services/api';import {getCachedDate,getCachedMonth,replaceCachedMonth,saveOfflineNote,updateCachedUser} from './services/offlineStore';import {syncPendingChanges} from './services/sync';import type {Note,NoteNotification,RecurringEvent,RecurringEventInput,User} from './types/note';import {isoDate,monthKey,monthTitle,shiftMonth} from './utils/date';import {recurringNotes} from './utils/recurrence'
const USER_KEY='key3in-user'
export default function App(){
 const [user,setUserState]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem(USER_KEY)??'null')}catch{return null}}),[authReady,setAuthReady]=useState(false),[view,setView]=useState<'calendar'|'search'|'notifications'|'settings'|'recurring'>('calendar'),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[cache,setCache]=useState<Record<string,Note[]>>({}),[loading,setLoading]=useState(false),[editor,setEditor]=useState<{date:string;initial:string;notes:Note[];returnView:'calendar'|'search'|'notifications'}|null>(null),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[highlight,setHighlight]=useState<string|null>(null),[direction,setDirection]=useState(0),[notifications,setNotifications]=useState<NoteNotification[]>([]),[recurring,setRecurring]=useState<RecurringEvent[]>([])
 const loaded=useRef(new Set<string>()),syncingRef=useRef(false),knownNotificationIds=useRef<Set<number>|null>(null),online=useOnlineStatus(),key=monthKey(month),notes=cache[key]??[]
 const noteMap=useMemo(()=>{const recurringInGrid=[-1,0,1].flatMap(offset=>recurringNotes(recurring,monthKey(shiftMonth(month,offset))));const map=new Map<string,Note[]>();for(const note of [...notes,...recurringInGrid])map.set(note.date,[...(map.get(note.date)??[]),note]);return map},[notes,recurring,month])
 const setUser=useCallback((value:User|null)=>{setUserState(value);if(value)localStorage.setItem(USER_KEY,JSON.stringify(value));else localStorage.removeItem(USER_KEY)},[])
 useEffect(()=>{if(!getToken()){setAuthReady(true);return}api.me().then(setUser).catch(error=>{if(error instanceof ApiError&&error.status===401){setToken(null);setUser(null)}}).finally(()=>setAuthReady(true))},[setUser])
 const loadLocal=useCallback(async(target:string,currentUser:User)=>{const stored=await getCachedMonth(currentUser.id,target);setCache(value=>({...value,[target]:stored}))},[])
 const synchronize=useCallback(async(notify=false)=>{if(!user||!navigator.onLine||syncingRef.current)return;syncingRef.current=true;try{const count=await syncPendingChanges(user.id);loaded.current.clear();await loadLocal(key,user);if(notify&&count)setMessage(`Синхронизировано заметок: ${count}`)}catch{setMessage('Синхронизация будет повторена при восстановлении связи')}finally{syncingRef.current=false}},[key,loadLocal,user])
 useEffect(()=>{if(!user)return;let active=true;(async()=>{setLoading(true);try{await loadLocal(key,user);if(navigator.onLine&&!loaded.current.has(key)){const remote=await api.month(month.getFullYear(),month.getMonth()+1);await replaceCachedMonth(user.id,key,remote);loaded.current.add(key);if(active)await loadLocal(key,user)}}catch(error){if(active)setMessage(error instanceof Error?error.message:'Не удалось открыть кэш')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[key,month,online,user,loadLocal])
 const announceNotification=useCallback((item:NoteNotification)=>{if('Notification' in window&&Notification.permission==='granted'){const title=`${item.user_name} добавил(а) заметку`,options={body:item.text,icon:`${import.meta.env.BASE_URL}icons/icon.svg`};if('serviceWorker' in navigator)void navigator.serviceWorker.ready.then(registration=>registration.showNotification(title,options)).catch(()=>new Notification(title,options));else new Notification(title,options)}navigator.vibrate?.([150,80,150]);try{const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=740;gain.gain.value=.08;oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.16);oscillator.onended=()=>void context.close()}catch{/* Звук может быть запрещён настройками браузера. */}},[])
 const loadNotifications=useCallback(async()=>{if(!user||!navigator.onLine)return;try{const incoming=await api.notifications(),previous=knownNotificationIds.current;if(previous)incoming.filter(item=>!item.is_read&&!previous.has(item.note_id)).forEach(announceNotification);knownNotificationIds.current=new Set(incoming.map(item=>item.note_id));setNotifications(incoming)}catch{/* Повторим запрос при следующем опросе. */}},[announceNotification,user])
 useEffect(()=>{if(user&&online)api.recurringEvents().then(setRecurring).catch(()=>{});},[user,online]);useEffect(()=>{if(!user||!online)return;void loadNotifications();const timer=setInterval(()=>void loadNotifications(),30000);return()=>clearInterval(timer)},[loadNotifications,online,user])
 useEffect(()=>{if(online)void synchronize(true)},[online,synchronize]);useEffect(()=>{if(!online||!user)return;const retry=()=>void synchronize(),timer=setInterval(retry,30000);window.addEventListener('focus',retry);return()=>{clearInterval(timer);window.removeEventListener('focus',retry)}},[online,synchronize,user])
 const move=useCallback((amount:number)=>{setDirection(amount);setMonth(value=>shiftMonth(value,amount))},[]),swipe=useSwipe(()=>move(1),()=>move(-1))
 const today=()=>{const now=new Date(),date=isoDate(now);setView('calendar');setMonth(new Date(now.getFullYear(),now.getMonth(),1));setHighlight(date);setTimeout(()=>document.getElementById(`day-${date}`)?.focus(),50);setTimeout(()=>setHighlight(null),1800)}
 const openDate=async(date:string,returnView:'calendar'|'search'|'notifications'='calendar')=>{if(!user)return;let dateNotes=noteMap.get(date)??[];if(returnView!=='calendar'){try{dateNotes=navigator.onLine?await api.date(date):await getCachedDate(user.id,date)}catch{dateNotes=await getCachedDate(user.id,date)}}const own=dateNotes.find(note=>note.user_id===user.id&&!note.recurring);setEditor({date,initial:own?.text??'',notes:dateNotes,returnView})}
 const save=async(text:string)=>{if(!editor||!user)return;setSaving(true);try{const local=await saveOfflineNote(user.id,user.name,user.color,editor.date,text),target=editor.date.slice(0,7);setCache(current=>{const list=current[target]??[],updated=local?[...list.filter(note=>!(note.date===editor.date&&note.user_id===user.id)),local]:list.filter(note=>!(note.date===editor.date&&note.user_id===user.id));return{...current,[target]:updated}});const returnView=editor.returnView;setEditor(null);setView(returnView);setMessage(navigator.onLine?'Заметка сохранена':'Заметка сохранена офлайн');if(navigator.onLine)await synchronize()}catch{setMessage('Не удалось сохранить заметку в локальный кэш')}finally{setSaving(false)}}
 const saveRecurring=async(value:RecurringEventInput,id?:number)=>{if(id)await api.updateRecurringEvent(id,value);else await api.createRecurringEvent(value);setRecurring(await api.recurringEvents())},deleteRecurring=async(id:number)=>{try{await api.deleteRecurringEvent(id);setRecurring(current=>current.filter(event=>event.id!==id));setMessage('Событие удалено')}catch(error){setMessage(error instanceof Error?error.message:'Не удалось удалить событие')}};const openNotifications=()=>{setView('notifications');if('Notification' in window&&Notification.permission==='default')void Notification.requestPermission()}
 const readNotification=async(item:NoteNotification)=>{try{if(!item.is_read)await api.readNotification(item.note_id);setNotifications(current=>current.map(value=>value.note_id===item.note_id?{...value,is_read:true}:value));await openDate(item.date,'notifications')}catch(error){setMessage(error instanceof Error?error.message:'Не удалось открыть уведомление')}}
 const readAllNotifications=async()=>{try{await api.readAllNotifications();setNotifications(current=>current.map(item=>({...item,is_read:true})))}catch(error){setMessage(error instanceof Error?error.message:'Не удалось прочитать уведомления')}}
 const logout=()=>{setToken(null);setUser(null);setCache({});setNotifications([]);knownNotificationIds.current=null;setView('calendar')},updateUser=async(name:string,color:string)=>{const updated=await api.updateMe(name,color);await updateCachedUser(updated.id,updated.name,updated.color);setCache(current=>Object.fromEntries(Object.entries(current).map(([monthNotes,value])=>[monthNotes,value.map(note=>note.user_id===updated.id?{...note,user_name:updated.name,user_color:updated.color}:note)])));setUser(updated);setMessage('Настройки сохранены')}
 if(!authReady)return <Box sx={{minHeight:'100dvh',display:'grid',placeItems:'center'}}><CircularProgress/></Box>;if(!user)return <><AuthScreen onSuccess={value=>{setUser(value);setAuthReady(true)}} onError={setMessage}/><Snackbar open={!!message} autoHideDuration={4000} onClose={()=>setMessage('')}><Alert severity="error">{message}</Alert></Snackbar></>
 return <Box sx={{height:'100dvh',overflow:'hidden',px:{xs:.75,sm:2},pb:'max(8px, env(safe-area-inset-bottom))',display:'flex',flexDirection:'column'}}><Box sx={{maxWidth:1000,mx:'auto',width:'100%',height:'100%',display:'flex',flexDirection:'column',minHeight:0}}><CalendarHeader title={monthTitle(month)} showMonth={view==='calendar'} hasUnread={notifications.some(item=>!item.is_read)} onPrevious={()=>move(-1)} onNext={()=>move(1)} onToday={today} onSearch={()=>setView('search')} onNotifications={openNotifications} onSettings={()=>setView('settings')} onRecurring={()=>setView('recurring')}/>{view==='recurring'?<RecurringEventsView events={recurring} userId={user.id} onBack={()=>setView('calendar')} onSave={saveRecurring} onDelete={deleteRecurring}/>:view==='settings'?<SettingsView user={user} onBack={()=>setView('calendar')} onSave={updateUser} onLogout={logout} onMessage={setMessage}/>:view==='notifications'?<NotificationsView notifications={notifications} onBack={()=>setView('calendar')} onRead={item=>void readNotification(item)} onReadAll={()=>void readAllNotifications()}/>:view==='search'?<SearchView query={query} setQuery={setQuery} online={online} userId={user.id} onClose={()=>setView('calendar')} onSelect={note=>void openDate(note.date,'search')} onError={setMessage}/>:<><Box {...swipe} key={key} sx={{touchAction:'pan-y',animation:`slide-${direction<0?'right':'left'} 240ms ease-out`,flex:1,minHeight:0}}><CalendarGrid month={month} notes={noteMap} loading={loading&&!cache[key]} highlight={highlight} onSelect={date=>void openDate(date)}/></Box></>}{editor&&<NoteEditor {...editor} userId={user.id} userName={user.name} userColor={user.color} onClose={()=>setEditor(null)} onSave={save} saving={saving}/>}</Box><Snackbar open={!!message} autoHideDuration={4000} onClose={()=>setMessage('')}><Alert severity="info">{message}</Alert></Snackbar></Box>
}
