import { useCallback,useEffect,useMemo,useState } from 'react';import { Alert,Box,Snackbar } from '@mui/material';import { CalendarHeader } from './components/CalendarHeader';import { CalendarGrid } from './components/CalendarGrid';import { NoteEditor } from './components/NoteEditor';import { SearchView } from './components/SearchView';import { useSwipe } from './hooks/useSwipe';import { api,ApiError } from './services/api';import type { Note } from './types/note';import { isoDate,monthKey,monthTitle,shiftMonth } from './utils/date'
export default function App(){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const [cache,setCache]=useState<Record<string,Note[]>>({});const [loading,setLoading]=useState(false);const [editor,setEditor]=useState<{date:string;initial:string;fromSearch:boolean}|null>(null);const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[highlight,setHighlight]=useState<string|null>(null),[direction,setDirection]=useState(0)
 const key=monthKey(month),notes=cache[key]??[];const noteMap=useMemo(()=>new Map(notes.map(n=>[n.date,n])),[notes])
 useEffect(()=>{if(cache[key])return;setLoading(true);api.month(month.getFullYear(),month.getMonth()+1).then(data=>setCache(c=>({...c,[key]:data}))).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[key,month,cache])
 const move=useCallback((amount:number)=>{setDirection(amount);setMonth(current=>shiftMonth(current,amount))},[]);const swipe=useSwipe(()=>move(1),()=>move(-1));
 const today=()=>{const now=new Date(),date=isoDate(now);setMonth(new Date(now.getFullYear(),now.getMonth(),1));setHighlight(date);setTimeout(()=>document.getElementById(`day-${date}`)?.focus({preventScroll:false}),50);setTimeout(()=>setHighlight(null),1800)}
 const openDate=(date:string,fromSearch=false,text?:string)=>setEditor({date,initial:text??noteMap.get(date)?.text??'',fromSearch})
 const save=async(text:string)=>{if(!editor)return;setSaving(true);const trimmed=text.trim();try{let saved:Note|undefined;if(editor.initial){saved=await api.update(editor.date,text)}else if(trimmed){saved=await api.create(editor.date,text)}const targetKey=editor.date.slice(0,7);setCache(current=>{const list=current[targetKey]??[];return {...current,[targetKey]:saved?[...list.filter(n=>n.date!==editor.date),saved].sort((a,b)=>a.date.localeCompare(b.date)):list.filter(n=>n.date!==editor.date)}});const fromSearch=editor.fromSearch;setEditor(null);setSearch(fromSearch);setMessage(trimmed?'Заметка сохранена':'Заметка удалена')}catch(e){setMessage(e instanceof ApiError?e.message:'Не удалось сохранить заметку')}finally{setSaving(false)}}
 const onError=useCallback((value:string)=>setMessage(value),[])
 return <Box sx={{minHeight:'100dvh',px:{xs:.75,sm:2},pb:'max(16px, env(safe-area-inset-bottom))'}}><Box sx={{maxWidth:1000,mx:'auto'}}>{search?<SearchView query={query} setQuery={setQuery} onClose={()=>setSearch(false)} onSelect={n=>openDate(n.date,true,n.text)} onError={onError}/>:<><CalendarHeader title={monthTitle(month)} onPrevious={()=>move(-1)} onNext={()=>move(1)} onToday={today} onSearch={()=>setSearch(true)}/><Box {...swipe} sx={{touchAction:'pan-y',animation:`slide-${direction<0?'right':'left'} 240ms ease-out`}} key={key}><CalendarGrid month={month} notes={noteMap} loading={loading&&!cache[key]} highlight={highlight} onSelect={openDate}/></Box></>}{editor&&<NoteEditor {...editor} onClose={()=>setEditor(null)} onSave={save} saving={saving}/>}</Box><Snackbar open={!!message} autoHideDuration={3500} onClose={()=>setMessage('')}><Alert severity={message.includes('сохранена')||message.includes('удалена')?'success':'error'}>{message}</Alert></Snackbar></Box>
}
