import {useCallback,useEffect,useMemo,useRef,useState} from 'react';import {Alert,Box,Chip,CircularProgress,Snackbar} from '@mui/material';import CloudDoneRounded from '@mui/icons-material/CloudDoneRounded';import CloudOffRounded from '@mui/icons-material/CloudOffRounded';import SyncRounded from '@mui/icons-material/SyncRounded';import {AuthScreen} from './components/AuthScreen';import {CalendarHeader} from './components/CalendarHeader';import {CalendarGrid} from './components/CalendarGrid';import {NoteEditor} from './components/NoteEditor';import {SearchView} from './components/SearchView';import {SettingsView} from './components/SettingsView';import {useOnlineStatus} from './hooks/useOnlineStatus';import {useSwipe} from './hooks/useSwipe';import {api,ApiError,getToken,setToken} from './services/api';import {getCachedDate,getCachedMonth,replaceCachedMonth,saveOfflineNote} from './services/offlineStore';import {syncPendingChanges} from './services/sync';import type {Note,User} from './types/note';import {isoDate,monthKey,monthTitle,shiftMonth} from './utils/date'
const USER_KEY='key3in-user'
export default function App(){
 const [user,setUserState]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem(USER_KEY)??'null')}catch{return null}}),[authReady,setAuthReady]=useState(false),[view,setView]=useState<'calendar'|'search'|'settings'>('calendar'),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[cache,setCache]=useState<Record<string,Note[]>>({}),[loading,setLoading]=useState(false),[editor,setEditor]=useState<{date:string;initial:string;fromSearch:boolean}|null>(null),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[highlight,setHighlight]=useState<string|null>(null),[direction,setDirection]=useState(0)
 const loaded=useRef(new Set<string>()),syncingRef=useRef(false),online=useOnlineStatus(),key=monthKey(month),notes=cache[key]??[]
 const noteMap=useMemo(()=>{const map=new Map<string,Note[]>();for(const note of notes)map.set(note.date,[...(map.get(note.date)??[]),note]);return map},[notes])
 const setUser=useCallback((value:User|null)=>{setUserState(value);if(value)localStorage.setItem(USER_KEY,JSON.stringify(value));else localStorage.removeItem(USER_KEY)},[])
 useEffect(()=>{if(!getToken()){setAuthReady(true);return}api.me().then(setUser).catch(error=>{if(error instanceof ApiError&&error.status===401){setToken(null);setUser(null)}}).finally(()=>setAuthReady(true))},[setUser])
 const loadLocal=useCallback(async(target:string,currentUser:User)=>{const stored=await getCachedMonth(currentUser.id,target);setCache(value=>({...value,[target]:stored}))},[])
 const synchronize=useCallback(async(notify=false)=>{if(!user||!navigator.onLine||syncingRef.current)return;syncingRef.current=true;setSyncing(true);try{const count=await syncPendingChanges(user.id);loaded.current.clear();await loadLocal(key,user);if(notify&&count)setMessage(`Синхронизировано заметок: ${count}`)}catch{setMessage('Синхронизация будет повторена при восстановлении связи')}finally{syncingRef.current=false;setSyncing(false)}},[key,loadLocal,user])
 useEffect(()=>{if(!user)return;let active=true;(async()=>{setLoading(true);try{await loadLocal(key,user);if(navigator.onLine&&!loaded.current.has(key)){const remote=await api.month(month.getFullYear(),month.getMonth()+1);await replaceCachedMonth(user.id,key,remote);loaded.current.add(key);if(active)await loadLocal(key,user)}}catch(error){if(active)setMessage(error instanceof Error?error.message:'Не удалось открыть кэш')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[key,month,online,user,loadLocal])
 useEffect(()=>{if(online)void synchronize(true)},[online,synchronize]);useEffect(()=>{if(!online||!user)return;const retry=()=>void synchronize(),timer=setInterval(retry,30000);window.addEventListener('focus',retry);return()=>{clearInterval(timer);window.removeEventListener('focus',retry)}},[online,synchronize,user])
 const move=useCallback((amount:number)=>{setDirection(amount);setMonth(value=>shiftMonth(value,amount))},[]),swipe=useSwipe(()=>move(1),()=>move(-1))
 const today=()=>{const now=new Date(),date=isoDate(now);setMonth(new Date(now.getFullYear(),now.getMonth(),1));setHighlight(date);setTimeout(()=>document.getElementById(`day-${date}`)?.focus(),50);setTimeout(()=>setHighlight(null),1800)}
 const openDate=async(date:string,fromSearch=false)=>{let dateNotes=noteMap.get(date)??[];if(fromSearch){try{dateNotes=navigator.onLine?await api.date(date):await getCachedDate(user.id,date)}catch{dateNotes=await getCachedDate(user.id,date)}}const own=dateNotes.find(note=>note.user_id===user.id);setEditor({date,initial:own?.text??'',fromSearch})}
 const save=async(text:string)=>{if(!editor||!user)return;setSaving(true);try{const local=await saveOfflineNote(user.id,user.name,user.color,editor.date,text),target=editor.date.slice(0,7);setCache(current=>{const list=current[target]??[],updated=local?[...list.filter(note=>!(note.date===editor.date&&note.user_id===user.id)),local]:list.filter(note=>!(note.date===editor.date&&note.user_id===user.id));return{...current,[target]:updated}});const fromSearch=editor.fromSearch;setEditor(null);setView(fromSearch?'search':'calendar');setMessage(navigator.onLine?'Заметка сохранена':'Заметка сохранена офлайн');if(navigator.onLine)await synchronize()}catch{setMessage('Не удалось сохранить заметку в локальный кэш')}finally{setSaving(false)}}
 const logout=()=>{setToken(null);setUser(null);setCache({});setView('calendar')},updateUser=async(name:string,color:string)=>{const updated=await api.updateMe(name,color);setUser(updated);setMessage('Настройки сохранены')}
 if(!authReady)return <Box sx={{minHeight:'100dvh',display:'grid',placeItems:'center'}}><CircularProgress/></Box>;if(!user)return <><AuthScreen onSuccess={value=>{setUser(value);setAuthReady(true)}} onError={setMessage}/><Snackbar open={!!message} autoHideDuration={4000} onClose={()=>setMessage('')}><Alert severity="error">{message}</Alert></Snackbar></>
 return <Box sx={{height:'100dvh',overflow:'hidden',px:{xs:.75,sm:2},pb:'max(8px, env(safe-area-inset-bottom))',display:'flex',flexDirection:'column'}}><Box sx={{maxWidth:1000,mx:'auto',width:'100%',height:'100%',display:'flex',flexDirection:'column',minHeight:0}}><Box sx={{display:'flex',justifyContent:'flex-end',pt:.5}} aria-live="polite"><Chip size="small" color={online?'default':'warning'} icon={syncing?<SyncRounded className="sync-icon"/>:online?<CloudDoneRounded/>:<CloudOffRounded/>} label={syncing?'Синхронизация':online?'Онлайн':'Офлайн'}/></Box>{view==='settings'?<SettingsView user={user} onBack={()=>setView('calendar')} onSave={updateUser} onLogout={logout} onMessage={setMessage}/>:view==='search'?<SearchView query={query} setQuery={setQuery} online={online} userId={user.id} onClose={()=>setView('calendar')} onSelect={note=>void openDate(note.date,true)} onError={setMessage}/>:<><CalendarHeader title={monthTitle(month)} onPrevious={()=>move(-1)} onNext={()=>move(1)} onToday={today} onSearch={()=>setView('search')} onSettings={()=>setView('settings')}/><Box {...swipe} key={key} sx={{touchAction:'pan-y',animation:`slide-${direction<0?'right':'left'} 240ms ease-out`,flex:1,minHeight:0}}><CalendarGrid month={month} notes={noteMap} loading={loading&&!cache[key]} highlight={highlight} onSelect={date=>void openDate(date)}/></Box></>}{editor&&<NoteEditor {...editor} onClose={()=>setEditor(null)} onSave={save} saving={saving}/>}</Box><Snackbar open={!!message} autoHideDuration={4000} onClose={()=>setMessage('')}><Alert severity="info">{message}</Alert></Snackbar></Box>
}
